spring:
  application:
    name: jeecg-system
  config:
    import: optional:classpath:config/application-liteflow.yml
  profiles:
    active: '@profile.name@'

erp:
  authUrl: http://192.168.6.134/k3cloud/Kingdee.BOS.WebApi.ServicesStub.AuthService.LoginByAppSecret.common.kdsvc
  queryUrl: http://192.168.6.134/K3Cloud/Kingdee.BOS.WebApi.ServicesStub.DynamicFormService.ExecuteBillQuery.common.kdsvc
  acctID: '6a044c2a46383c'
  appId: '347934_RZbrX8HKyvCaR/XJX11CyYUNzi5WSCKO'
  appSecret: '3fd789c00b9342eea0d7ef3dff5894c0'
  lcid: '2052'
  username: '全功能'
  headerKey: 'kdservice-sessionid'
  headerToken:
  connect-timeout-millis: 15000
  read-timeout-millis: 120000
